# site settings

title: pswish | Vet & CS Student
description: Portfolio site and blog for Paul
taglong: Portfolio site and blog for Paul
tagshort: Paul's site 
url: https://pswish.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/pswish/pswish.github.io

# author settings

author:
  name: Paul Swisher
  email: pswish@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: pswish

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"