# site settings

title: Paul Swisher | Veteran • Systems Engineer • Researcher
description: Systems engineer, US military veteran, and independent researcher with three patents pending.
taglong: Systems engineer, US military veteran, and independent researcher with three patents pending.
tagshort: Paul Swisher 
url: https://pswish.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/pswish/pswish.github.io

# author settings

author:
  name: Paul Swisher
  email: paul@paulswisher.co
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: pswish

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 7
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"